# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: devFancy
brief-intro: BE Developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
# url에 임의의 값을 넣으면
# {{site.url}} 사용시 local 환경에서도 지정한 값을 사용한다.
    

permalink: /:title/

# other links
github_username: devFancy
linkedIn_username: junyong-moon-479385264
insta_username: junyongmoon
# facebook_username:
# email: fancy.junyongmoon@gmail.com

description_footer: ""

# comments
# two ways to comment, only choose one, and use your own short name
#disqus_shortname: devFancy

# Statistic Analysis 
google_analytics_id: G-7BMWW1711K # google analytics id

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  sass_dir:         _sass
  style:            compressed

# port (default = 4000)
# port: 4000

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n"

# paginate
plugins: [jekyll-paginate]
paginate: 5

future: true
incremental: false
regenerate : true

# categoties order
## 'categories_order' 항목을 추가하여 카테고리 순서를 정적으로 설정
## 이를 통해 메인 페이지 및 카테고리 페이지에서 카테고리 순서가 고정
categories_order:
  - "DevHistory"
  - "Java"
  - "Spring"
  - "SpringBoot"
  - "JPA"
  - "MySQL"
  - "Flyway"
  - "Kafka"
  - "Technology"
  - "GoodCode"
  - "Side_Project"
  - "Retrospective"
  - "AlgorithmSkill"
  - "LeetCode"
  - "Algorithm"
  - "SQL"
  - "OS"
  - "Database"
  - "Network"
  - "HTTP"
  - "DataStructure"
  - "Linux"
  - "Woowacourse"
  - "Git"
  - "AssertJ"
  - "IntelliJ"
  - "Probability-Statistics"
  - "Electronic-Finance"
  - "Business-Statistics"
  - "Competition"
  - "Book"
  - "Workout"
  - "E.T.C"
